const OK_STATUS_CODE = 200;

const OK_CREATE_STATUS_CODE = 201;

const BAD_REQUEST_STATUS_CODE = 400;

const UNAUTHORIZED_STATUS_CODE = 401;

const NOT_FOUND_STATUS_CODE = 404;

const DUPLICATE_STATUS_CODE = 409;

const SERVER_ERROR_STAUS_CODE = 500;

module.exports = {
  OK_STATUS_CODE,
  OK_CREATE_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  SERVER_ERROR_STAUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  DUPLICATE_STATUS_CODE,
};
